"""f1_initial_schema_solves_sessions

Revision ID: 1cbfe3113a0f
Revises:
Create Date: 2026-05-02 12:55:31.880145

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cbfe3113a0f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("scramble_type", sa.String(length=32), nullable=True),
        sa.Column("cstimer_session_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_cstimer_session_id"), "sessions", ["cstimer_session_id"], unique=True
    )
    op.create_index(op.f("ix_sessions_name"), "sessions", ["name"], unique=False)
    op.create_table(
        "solves",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("time_ms", sa.Integer(), nullable=False),
        sa.Column("cube_type", sa.String(length=32), nullable=False),
        sa.Column("scramble", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("plus_two", sa.Boolean(), nullable=False),
        sa.Column("dnf", sa.Boolean(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("hardware_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_solves_cube_type"), "solves", ["cube_type"], unique=False)
    op.create_index(
        "ix_solves_cube_type_timestamp", "solves", ["cube_type", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_solves_hardware_id"), "solves", ["hardware_id"], unique=False)
    op.create_index(op.f("ix_solves_session_id"), "solves", ["session_id"], unique=False)
    op.create_index(
        "ix_solves_session_timestamp", "solves", ["session_id", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_solves_timestamp"), "solves", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_solves_timestamp"), table_name="solves")
    op.drop_index("ix_solves_session_timestamp", table_name="solves")
    op.drop_index(op.f("ix_solves_session_id"), table_name="solves")
    op.drop_index(op.f("ix_solves_hardware_id"), table_name="solves")
    op.drop_index("ix_solves_cube_type_timestamp", table_name="solves")
    op.drop_index(op.f("ix_solves_cube_type"), table_name="solves")
    op.drop_table("solves")
    op.drop_index(op.f("ix_sessions_name"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_cstimer_session_id"), table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
