"""add challenges table

Revision ID: 251693e1a6b2
Revises: 10f994e2060d
Create Date: 2026-05-03 11:54:19.627646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "251693e1a6b2"
down_revision: Union[str, Sequence[str], None] = "10f994e2060d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("cube_type", sa.String(length=32), nullable=True),
        sa.Column("params_json", sa.Text(), nullable=True),
        sa.Column("target_value", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("generated_for_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_challenges_generated_for_date"), "challenges", ["generated_for_date"], unique=False
    )
    op.create_index(op.f("ix_challenges_kind"), "challenges", ["kind"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_challenges_kind"), table_name="challenges")
    op.drop_index(op.f("ix_challenges_generated_for_date"), table_name="challenges")
    op.drop_table("challenges")
    # ### end Alembic commands ###
