"""add notes to session

Revision ID: 4e772ce9ed1e
Revises: 20cf366641e1
Create Date: 2026-05-03 09:54:45.793748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e772ce9ed1e"
down_revision: Union[str, Sequence[str], None] = "20cf366641e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "notes")
    # ### end Alembic commands ###
