"""add solve.split_times_ms for multi-phase splits

Revision ID: 593bfa59e08b
Revises: db68e5f4cdae
Create Date: 2026-05-03 18:30:49.815957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "593bfa59e08b"
down_revision: Union[str, Sequence[str], None] = "db68e5f4cdae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("solves", sa.Column("split_times_ms", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("solves", "split_times_ms")
    # ### end Alembic commands ###
