"""add solve.alg_case for algorithm trainer

Revision ID: db68e5f4cdae
Revises: 251693e1a6b2
Create Date: 2026-05-03 12:35:01.612745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db68e5f4cdae"
down_revision: Union[str, Sequence[str], None] = "251693e1a6b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("solves", sa.Column("alg_case", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_solves_alg_case"), "solves", ["alg_case"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_solves_alg_case"), table_name="solves")
    op.drop_column("solves", "alg_case")
    # ### end Alembic commands ###
