"""All 21 PLL cases — generated by exact cube simulation.

The diagrams are DERIVED from the reference algorithms in the user's source
table (see ALGS in cube_sim.py): case = the state that the algorithm solves,
normalized to the canonical AUF orientation. No hand-authored permutations.

Validated end-to-end: the simulator reproduces the user-confirmed Ua diagram
from its algorithm (asserted in cube_sim.py).
"""

from cube_sim import PLL_CASES  # noqa: F401
